#!/bin/bash
#Command to run this script is ./NGS.sh sample1
#eg ./NGS.sh 549

echo "***************"
echo "Mats NGS Report Pipeline"
echo "***************"

#Run Number
RunCode=FEVR101

#Enter sample name below
sample1=$1

###Paths to files###
hg19_buildpath=/mnt/d/hg19
hg38_buildpath=/mnt/d/hg38
ToolPath=~
DataPath=/mnt/d/$RunCode
TempPath=$DataPath/temp
mkdir -p $TempPath

unzip_fastq(){
echo "Unzipping fastq"
echo $sample1
gzip -dk $DataPath/$sample1-R1.fastq.gz
gzip -dk $DataPath/$sample1-R2.fastq.gz

head $DataPath/$sample1-R1.fastq > $DataPath/$sample1-R1.header.txt
head $DataPath/$sample1-R2.fastq > $DataPath/$sample1-R2.header.txt
}

report_data_grabber(){
#Report header
 printf "%b\n" "The following report was generated by Mat Nightingale at the Dalhousie Genomics Core." \
 "If anything is unclear contact Genomics@Dal.ca" \
 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" \ > $DataPath/NGS_report_text.txt
 
#Get TOTAL_READS from hybrid_selection_metrics. Column 23 Row 8
awk 'FNR == 7 {print $23}' $DataPath/$sample1.hybrid_selection_metrics >> $DataPath/NGS_report_text.txt
awk 'FNR == 8 {print $23}' $DataPath/$sample1.hybrid_selection_metrics >> $DataPath/NGS_report_text.txt
printf "%b\n" >> $DataPath/NGS_report_text.txt

#Get MEAN_TARGET_COVERAGE from hybrid_selection_metrics. Column 34 Row 8
awk 'FNR == 7 {print $34}' $DataPath/$sample1.hybrid_selection_metrics >> $DataPath/NGS_report_text.txt
awk 'FNR == 8 {print $34}' $DataPath/$sample1.hybrid_selection_metrics >> $DataPath/NGS_report_text.txt
printf "%b\n" >> $DataPath/NGS_report_text.txt

#Get Quality Score from unmapped.unmapped.quality_yield_metrics. Column 8 Row 7
printf "%b\n" "Q30 Calculation" >> $DataPath/NGS_report_text.txt
awk 'FNR == 7 {print $4}' $DataPath/$sample1.unmapped.unmapped.quality_yield_metrics >> $DataPath/NGS_report_text.txt
awk 'FNR == 8 {print $4}' $DataPath/$sample1.unmapped.unmapped.quality_yield_metrics >> $DataPath/NGS_report_text.txt
printf "%b\n" >> $DataPath/NGS_report_text.txt
awk 'FNR == 7 {print $8}' $DataPath/$sample1.unmapped.unmapped.quality_yield_metrics >> $DataPath/NGS_report_text.txt
awk 'FNR == 8 {print $8}' $DataPath/$sample1.unmapped.unmapped.quality_yield_metrics >> $DataPath/NGS_report_text.txt
printf "%b\n" >> $DataPath/NGS_report_text.txt
}

#unzip_fastq
report_data_grabber

<<to_add

to_add